FROM node:16.17.0-bullseye

WORKDIR /projects

RUN npm install -fg yarn \
    && npm install -fg create-react-app \
    && react-app raectjs npm install -g create-react-app test --template typescript\
    && yarn add @mui/material @mui/styled-engine-sc styled-components


