version: '3'

services:

  reactjs:
    build: 
      context: ./projects/
      dockerfile: Dockerfile
    tty: true
    environment:
    - NODE_ENV=production
    volumes:
    - ./projects:/projects
    command: 
      bash -c "cd test && yarn start"
    ports: 
    - 3000:3000
    # env_file: .env